name: Deploy master

on:
  push:
    branches:
      - master

jobs:
  build&deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: NPM install and build
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
    - name: Deploy to UpCloud
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-a -v -z -r --delete"
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        FOLDER: "dist/"
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USERNAME: ${{ secrets.USERNAME }}
        SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
    - name: Send Telegram message with args.
      uses: appleboy/telegram-action@master
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      with:
        args: The ${{ github.repository }} GitHub repository finish the ${{ github.event_name }} event on ${{ secrets.SERVER_IP }}.
